### ISSUE TITLE
Any demo of this?

### ISSUE THREAD

**Issue by uhlhosting** [DGAC/MattermostModule#23]
Can we get a preview or some demo version?

**Comment by BrunoSpy** [comment]
Hi,
There is no demo avalaible but I can answer your questions.

**Comment by BrunoSpy** [comment]
I just added a screenshot (not the latest version but it gives a good idea).

**Comment by uhlhosting** [comment]
Thank you! Will give it a spin.

**Comment by BrunoSpy** [comment]
Did you end up using this module ?

**Comment by uhlhosting** [comment]
not yet....
